
version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: abu
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: data_engineering
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./data_files:/docker-entrypoint-initdb.d
      # Mount your dataset folder inside the container
      - pg_data:/var/lib/postgresql/data   # Persistent PostgreSQL data
      - ./scripts:/docker-entrypoint-initdb.d  # Store your SQL scripts      
      - /home/abuammar/Documents/practice_DE_PROJECT/sql-data-warehouse-project-main/datasets:/tmp/csv/datasets

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres
volumes:
  pg_data:
