version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: abuAmmar
      POSTGRES_PASSWORD: Ammar2025   
      POSTGRES_DB: data_engineering
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Single init folder
      - /home/abuammar/Documents/practice_DE_PROJECT/sql-data-warehouse-project-main/datasets:/tmp/csv/datasets

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    depends_on:
      - postgres

volumes:
  pg_data:
